#!/bin/bash
dir="$1"
list="$2"

if [ -z "$list" ]; then
  echo 'Usage: taskdunstify <TASK DIR> <TASK LIST FILE>'
  exit 1
fi

IFS=$'\n'

for line in $(/PATH_TO/t.py --task-dir "$dir" --list "$list" --overdue --verbose)
do
  id=$(echo "$line" | grep -Po '^[a-z0-9]+(?= +-)')
  task=$(echo "$line" | grep -Po '\- .+$')
  action=$(/usr/local/bin/dunstify \
    --appname=task \
    --urgency=crit \
    --timeout=10000 \
    --action="xdelete,Delete" \
    --action="shift_1_week,Shift 1 week" \
    --action="shift_1_day,Shift tomorrow" \
    --action="shift_3_hours,Shift 3 hours" \
    --action="default,Shift next hour" \
    --action="finish,Finish" \
    --hints=string:synchronous:task_"$id" \
    "${task:2}")

  case "$action" in
  "default")
      /PATH_TO/t.py --task-dir "$dir" --list "$list" -s "$id" "+1 hour"
      /usr/local/bin/dunstctl close
      ;;
  "shift_3_hours")
      /PATH_TO/t.py --task-dir "$dir" --list "$list" -s "$id" "+3 hour"
      /usr/local/bin/dunstctl close
      ;;
  "shift_1_day")
      /PATH_TO/t.py --task-dir "$dir" --list "$list" -s "$id" "tomorrow"
      /usr/local/bin/dunstctl close
      ;;
  "shift_1_week")
      /PATH_TO/t.py --task-dir "$dir" --list "$list" -s "$id" "next week"
      /usr/local/bin/dunstctl close
      ;;
  "finish")
      /PATH_TO/t.py --task-dir "$dir" --list "$list" -f "$id"
      /usr/local/bin/dunstctl close
      ;;
  "xdelete")
      /PATH_TO/t.py --task-dir "$dir" --list "$list" -r "$id"
      /usr/local/bin/dunstctl close
      ;;
  esac
done
